# Generated by Django 5.0.6 on 2026-07-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('Sedan', 'Sedan'),
                            ('SUV', 'SUV'),
                            ('Truck', 'Truck'),
                            ('Coupe', 'Coupe'),
                            ('Wagon', 'Wagon'),
                        ],
                        default='Sedan',
                        max_length=10,
                    ),
                ),
                ('year', models.IntegerField(default=2025)),
                (
                    'dealer_id',
                    models.IntegerField(
                        help_text='ID of the dealership (from the Node/Mongo service) that carries this model'
                    ),
                ),
                (
                    'car_make',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='models',
                        to='djangoapp.carmake',
                    ),
                ),
            ],
        ),
    ]
